common/models/Destination.php
<?php
namespace common\models;

use yii\db\ActiveRecord;
use yii\db\Query;

class Destination extends ActiveRecord
{
    public static function tableName()
    {
        return 'tbl_destination';
    }

    /*
      * Return query
    */ 
    public function getByFilters($search)
    {
        $query = self::find();
        if(isset($search['keyword']) && trim($search['keyword'])!='') {
            $query->andWhere(['LIKE', 'name', $search['keyword']]);
        }
        if(isset($search['sort']) && $search['sort']) {
            $query->orderBy($search['sort']);
        }
        return $query;
    }

    public function getOne($tour_id)
    {
        $query = (new Query);
        
    }

    public function getDestinations($array_ids=array())
    {
        $destinations = self::find()
                ->select('id, name, alias, image')
                ->where(['IN', 'id', $array_ids])
                ->orderBy(['id' => $array_ids])
                ->all();
        return $destinations;
    }

}

backend/controllers/DestinationController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\Destination;
use yii\helpers\Url;
use yii\data\Pagination;
use common\models\Common;

/**
 * Site controller
 */
class DestinationController extends Controller
{

    public function actionIndex()
    {
        $search = Yii::$app->request->get();
        $query = (new Destination)->getByFilters($search);
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count()]);
        $items = $query->offset($pages->offset)
                ->limit($pages->limit)
                ->all();

        return $this->render('index', [
            'items' => $items,
            'pages' => $pages
        ]);
    }

    public function actionEdit()
    {
        $destination_id = Yii::$app->request->get('id');
        $destination = Destination::findOne($destination_id);

        if(Yii::$app->request->isPost) {
            $destination->name = Yii::$app->request->post('name');
            $destination->alias = Common::convertToAlias($destination->name);
            $destination->image = Yii::$app->request->post('image');
            $destination->status = Yii::$app->request->post('status');
            $destination->featured = Yii::$app->request->post('featured');
            if($destination->save()) {
                Yii::$app->session->setFlash('form_message', '<div class="alert alert-success">Cập nhật thành công</div>');
            }
            else {
                Yii::$app->session->setFlash('form_message', '<div class="alert alert-danger">Cập nhật thất bại</div>');
            }
        }

        return $this->render('edit', [
            'destination'=>$destination
        ]);
    }

    public function actionCreate()
    {
        $model = new Destination();
        if (Yii::$app->request->isPost) {
            $existDestination = $this->existDestinationByName(Yii::$app->request->post('name'));
            if($existDestination) {
                Yii::$app->session->setFlash('form_message', '<div class="alert alert-danger">Đã tồn tại địa điểm này</div>');
            }
            else {
                $model->name = Yii::$app->request->post('name');
                $model->alias = Common::convertToAlias($model->name);
                $model->type = Yii::$app->request->post('type', 'vietnam');
                $model->image = Yii::$app->request->post('image');
                if($model->save()) {
                    Yii::$app->session->setFlash('form_message', '<div class="alert alert-success">Thêm mới thành công</div>');
                    $this->createDestinationJsonFile();
                    return $this->redirect(Url::toRoute(['destination/edit', 'id'=>$model->id]));
                }
                else {
                    Yii::$app->session->setFlash('form_message', '<div class="alert alert-danger">Thêm mới thất bại</div>');
                }
            }
        }
        return $this->render('new');
    }

    public function existDestinationByName($destination_name)
    {
        $destination = Destination::findOne(['name'=>trim($destination_name)]);
        return $destination ? true : false;
    }

    public function createDestinationJsonFile()
    {
        $destinations = Destination::findAll(['status'=>1]);
        $data = array();
        foreach ($destinations as $destination ) {
            array_push($data, ['value'=>$destination['id'], 'text'=>$destination['name']]);
        }
        $fp = fopen('json/destinations.json', 'w');
        fwrite($fp, json_encode($data));
        fclose($fp);
    }
}

backend/views/destination/_form.php
<?php
use common\components\MyUtil;
?>
<form action="" method="POST">
    <div class="row">
        <div class="col-sm-9">
            <?php if(Yii::$app->session->hasFlash('form_message')) : ?>
            <div class="form-group"><?php echo Yii::$app->session->getFlash('form_message'); ?></div>
            <?php endif ?>
            <div class="form-group">
                <label for="">Tên địa điểm du lịch</label>
                <input type="text" name="name" placeholder="Tên địa điểm" class="form-control" value="<?php if(isset($destination['name'])) echo $destination['name'] ?>" required>
            </div>
            <div class="form-group">
                <label for="">Mô tả</label>
                <textarea name="description" class="editor"><?php if(isset($destination['description'])) echo $destination['description'] ?></textarea>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success">Cập nhật</button>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="form-group">
                <div class="box">
                    <label for="">Chọn thể loại</label>
                    <select name="type" class="form-control">
                        <option value="vietnam" <?php if($destination['status']=='vietnam') echo 'selected' ?>>Trong nước</option>
                        <option value="world" <?php if($destination['status']=='world') echo 'selected' ?>>Quốc tế</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <div class="box">
                    <label for="">Nổi bật <i class="fa fa-star"></i></label>
                    <select name="featured" class="form-control">
                        <option value="0" <?php if($destination['featured']=='0') echo 'selected' ?>>Không nổi bật</option>
                        <option value="1" <?php if($destination['featured']=='1') echo 'selected' ?>>Nổi bật</option>
                    </select>
                </div>
            </div>
            <?php if(isset($destination['status'])) : ?>
            <div class="form-group">
                <div class="box">
                    <label for="">Trạng thái</label>
                    <select name="status" class="form-control">
                        <option value="0" <?php if($destination['status']=='0') echo 'selected' ?>>Không hiển thị</option>
                        <option value="1" <?php if($destination['status']=='1') echo 'selected' ?>>Hiển thị</option>
                    </select>
                </div>
            </div>
            <?php endif ?>

            <div class="form-group">
                <div class="box">
                    <label for="">Ảnh đại diện</label>
                    <div class="image-preview">
                        <?php if($destination['image']) : ?>
                        <div class="gallery-item">
                            <span class="remove">&times;</span>
                            <img src="<?php echo $destination['image'] ?>" alt="">
                        </div>
                        <?php endif ?>
                    </div>
                    <a href="javascript:void(0)" class="btn btn-secondary" onClick="openPopup('<?php echo MyUtil::baseUrl() ?>/filemanager/dialog.php?type=1&field_id=destination_image&popup=1')">Ảnh đại diện</a>
                    <input id="destination_image" type="hidden" value="<?php if(isset($destination['image'])) echo $destination['image'] ?>" name="image">
                </div>
            </div>

        </div>
    </div>
</form>
<?php 
$this->registerJsFile('@web/js/filemanager.js', ['depends'=>[yii\web\JqueryAsset::className()]]);

backend/views/destination/edit.php
<?php  
echo $this->render('_form', ['destination'=>$destination]);
?>

backend/views/destination/index.php
<?php  
use yii\helpers\Url;
use yii\widgets\LinkPager;
?>
<form action="" method="GET">
    <div class="form-group">
        <input type="text" name="keyword" placeholder="Nhập tên địa điểm" value="<?php echo Yii::$app->request->get('keyword') ?>" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Tìm kiếm</button>
    <a href="<?php echo Url::toRoute('destination/create') ?>" class="btn btn-success">Thêm mới</a>

    <div class="mb-3"></div>
    <table class="table table-light">
        <thead>
            <tr>
                <td>#</td>
                <td>Ảnh đại diện</td>
                <td>Tên địa điểm</td>
            </tr>
        </thead>
        <tbody>
            <?php foreach($items as $item) : ?>
                <tr>
                    <td></td>
                    <td><img src="<?php echo $item['image'] ?>" alt="<?php echo $item['name'] ?>" class="img-thumb"></td>
                    <td><a href="<?php echo Url::toRoute(['destination/edit', 'id'=>$item['id']]) ?>"><?php echo $item['name'] ?></a></td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
    <?php echo LinkPager::widget([
            'pagination' => $pages,
        ]); ?>  
</form>

backend/views/destination/new.php
<?php  
$destination = Yii::$app->request->post();

echo $this->render('_form', ['destination'=>$destination]);
?>