frontend/controllers/BlogController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use yii\helpers\Url;
use common\models\Article;
use common\models\Tour;
use common\models\ArticleCategory;
use yii\data\Pagination;

/**
 * Site controller
 */
class BlogController extends Controller
{
    public function actionIndex()
    {
        $search = [
            'sort' => [
                'featured' => 'SORT_DESC',
                'publish_up' => 'SORT_DESC'
            ]
        ];
        $query = (new Article)->getByFilters($search);
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count()]);
        $items = $query->offset($pages->offset)
                ->limit($pages->limit)
                ->all();
        
        $tours = (new Tour)->getSaleTours();
        return $this->render('index', [
            'items' => $items,
            'tours' => $tours,
            'pages' => $pages
        ]);
    }

    public function actionCategory()
    {
        $cat_id = Yii::$app->request->get('cat_id');
        $search = [
            'cat_id' => $cat_id,
            'sort' => [
                'publish_up' => 'SORT_DESC'
            ]
        ];
        $query = (new Article)->getByFilters($search);
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count()]);
        $items = $query->offset($pages->offset)
                ->limit($pages->limit)
                ->all();
                
        return $this->render('category', [
            'items' => $items,
            'pages' => $pages
        ]);
    }

    public function actionDetail()
    {
        $article_id = Yii::$app->request->get('article_id');
        $article = (new Article)->getDetail($article_id);
        if(!$article) {
            return $this->redirect(Url::toRoute('site/error'));
        }
        return $this->render('detail', [
            'article' => $article
        ]);
    }
}

frontend/views/blog/detail.php
<?php  
use yii\helpers\Url;
use yii\widgets\Breadcrumbs;
use kartik\social\FacebookPlugin; 
use kartik\social\GooglePlugin;

$this->title = $article['title'];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="breadcrumbs-wrap">
    <div class="container">
        <?php echo Breadcrumbs::widget([
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]); ?>
    </div>
</div>
<div class="blog-detail_wrap">
    <div class="blog-container container">
        <div class="blog-header">
                <h1 class="blog-title"><?php echo $article['title'] ?></h1>
                <?php if($article['image']) : ?>
                <div class="blog-media">
                    <img src="<?php echo $article['image'] ?>" alt="<?php echo $this->title ?>">
                </div>
                <?php endif ?>
                <div class="blog-info">
                    <span class="autor"><i class="fa fa-user"></i> <?php echo $article['autor'] ?></span>
                    <span class="category"><a href="<?php echo Url::toRoute(['blog/category', 'cat_id'=>$article['cat_id'], 'alias'=>$article['cat_alias']]) ?>"><i class="fa fa-folder-open"></i> <?php echo $article['cat_title'] ?></a></span>
                    <span class="publish_up"><i class="fa fa-calendar"></i> <?php echo date('H:i d/m', strtotime($article['publish_up'])) ?></span>
                </div>
        </div>
        <div class="blog-body">
            <div class="blog-content">
                <?php echo $article['content'] ?>
            </div>
        </div>
        <div class="blog-footer">
            <ul class="social">
                <li><?php echo FacebookPlugin::widget(['type'=>FacebookPlugin::LIKE, 'settings' => ['size'=>'small', 'layout'=>'button']]); ?></li>
                <li><?php echo FacebookPlugin::widget(['type'=>FacebookPlugin::SHARE, 'settings' => ['size'=>'small', 'layout'=>'button_count', 'mobile_iframe'=>'false']]); ?></li>
                <li><?php echo GooglePlugin::widget(['pageId'=>'GOOGLE_PLUS_PAGE_ID']); ?></li>
            </ul>
            <div class="tags">
                <span class="tag-title"></span>
                <?php if(isset($tags) && $tags) : ?>
                    <?php foreach($tags as $tag) : ?>
                    <span class="tag-item"><a href="<?php echo Url::toRoute(['blog/tag', 'name'=>$tag['id'], 'alias'=>$tag['alias']]) ?>"><?php echo $tag['name'] ?></a></span>
                    <?php endforeach ?>
                <?php endif ?>
            </div>
        </div>
    </div>
</div>

frontend/views/blog/index.php
<?php  
use yii\helpers\Url;
use yii\widgets\Breadcrumbs;
use yii\widgets\LinkPager;
use frontend\components\TourWidget;
// use kartik\social\FacebookPlugin; 
// use kartik\social\GooglePlugin;

$this->title = isset($cat) && $cat ? $cat['title'] : 'Cẩm nang du lịch';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="breadcrumbs-wrap">
    <div class="container">
        <?php echo Breadcrumbs::widget([
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]); ?>
    </div>
</div>
<div class="blog-index_wrap container">
    <div class="row">
        <div class="col-sm-9">
            <div class="blog-header">
                <div class="grid-view">
                    <div class="view list_view active"><i class="material-icons">view_list</i></div>
                    <div class="view module_view"><i class="material-icons">view_module</i></div>
                </div>
            </div>
            <div class="blog-container">
                <?php foreach ($items as $item) {
                    echo $this->render('./item', ['article'=>$item]);
                } ?>
                <div class="blog-pagination">
                    <?php echo LinkPager::widget(['pagination' => $pages,]); ?>
                </div>
                
            </div>
        </div>
        <div class="col-sm-3">
            <div class="blog-right">
                <div class="box">
                    <h3 class="box-title">Tour nổi bật</h3>
                    <div class="content">
                        <?php foreach ($tours as $tour) : 
                            $images = json_decode($tour['images'], true);
                            $price = json_decode($tour['price'], true); ?>
            
                        <?php echo TourWidget::widget([
                                'id' => $tour['id'],
                                'title' => $tour['title'],
                                'alias' => $tour['alias'],
                                'base_price' => $price['base'],
                                'sale_price' => $price['sale'],
                                'duration_days' => $tour['duration_days'],
                                'duration_nights' => $tour['duration_nights'],
                                'featured' => $tour['featured'],
                                'image' => $images['intro'],
                                'custom_class' => 'quickview'
                            ]) ?>
            
                        <?php endforeach ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

frontend/views/blog/item.php
<?php  
use yii\helpers\Url;

?>
<div class="blog-item">
    <?php if($article['image']) : ?>
    <div class="blog-media">
        <img src="<?php echo $article['image'] ?>" alt="<?php echo $this->title ?>">
    </div>
    <h1 class="blog-title"><a href="<?php echo Url::toRoute(['blog/detail', 'article_id'=>$article['id'], 'alias'=>$article['alias']]) ?>"><?php echo $article['title'] ?></a></h1>
    <?php endif ?>
    <div class="blog-info">
        <span class="autor"><i class="fa fa-user"></i> <?php echo $article['autor'] ?></span>
        <span class="category"><a href="<?php echo Url::toRoute(['blog/category', 'cat_id'=>$article['cat_id'], 'alias'=>$article['cat_alias']]) ?>"><i class="fa fa-folder-open"></i> <?php echo $article['cat_title'] ?></a></span>
        <span class="entry-date"><i class="material-icons">event_note</i>
            <span class="entry-day"><?php echo  date('d', strtotime($article['publish_up'])) ?></span> 
            <span class="entry-month">Tháng <?php echo  date('m', strtotime($article['publish_up'])) ?></span>
        </span>
    </div>
    <div class="blog-introtext">
        <?php echo $article['intro_text'] ?>
    </div>
</div>