common/models/Tour.php
<?php
namespace common\models;

use Yii;
use yii\db\Expression;
use yii\db\ActiveRecord;
use yii\db\Query;
use common\models\Category;
use common\models\TourDeparture;
use common\models\TourDetail;
use common\models\Destination;
use common\models\Common;

class Tour extends ActiveRecord
{

    const HANOI = 'hanoi';
    const DANANG = 'danang';
    const HOCHIMINH = 'hcm';

    public static function tableName()
    {
        return 'tbl_tour';
    }

    /*
      * Return query
    */ 
    public function getByFilter($search)
    {
        $query = self::find();
        if(isset($search['departure_date']) && $search['departure_date']) {
            $query->leftJoin('tbl_tour_departures d', self::tableName() .'.id = d.tour_id');
        }
        if(isset($search['cat_id']) && $search['cat_id']) {
            $tourCatModel = new Category;
            $cats = $tourCatModel->getChildCatByParentId($search['cat_id'], true, true);
            $query->andWhere(['IN', 'cat_id', $search['cat_id']]);
        }
        if(isset($search['departure']) && $search['departure']) {
            $query->andWhere(['departure_location'=>$search['departure']]);
        }
        if(isset($search['departure_date']) && $search['departure_date']) {
            $departure_date = date('Y-m-d', strtotime($search['departure_date']));
            $query->andWhere(['>=', 'start_date', $departure_date]);
        }
        if(isset($search['destination']) && $search['destination']) {
            $arr_tours = $this->getToursBydDestinationKeyword($search['destination']);
            $query->andWhere(['IN', self::tableName() .'.id', $arr_tours]);
        }
        if(isset($search['duration']) && $search['duration']) {
            if(isset($search['duration']['from']) && $search['duration']['from']) {
                $query->andWhere(['>=', 'duration_days', $search['duration']['from']]);
            }
            if(isset($search['duration']['to']) && $search['duration']['to']) {
                $query->andWhere(['<=', 'duration_days', $search['duration']['to']]);
            }
        }
        if(isset($search['price']) && $search['price']) {
            $query->andWhere(['OR', 
                    ['AND', 
                        ['>=', new Expression("JSON_EXTRACT(". self::tableName() .".price, '$.base')"), $search['price']['from']], 
                        ['<=', new Expression("JSON_EXTRACT(". self::tableName() .".price, '$.base')"), $search['price']['to']]],
                    ['AND', 
                        ['>=', new Expression("JSON_EXTRACT(". self::tableName() .".price, '$.sale')"), $search['price']['from']], 
                        ['<=', new Expression("JSON_EXTRACT(". self::tableName() .".price, '$.sale')"), $search['price']['to']]]
                    ]);
        }
        if(isset($search['star']) && $search['star']) {
            $query->andWhere(['IN', new Expression("JSON_EXTRACT(". self::tableName() .".rating, '$.star')"), $search['star']]);
        }
        if(isset($search['featured'])) {
            $query->andWhere(['featured'=>$search['featured']]);
        }
        // $query->groupBy('tbl_tour.id');
        if(isset($search['sort']) && $search['sort']) {
            $query->orderBy($search['sort']);
        }
        return $query;
    }

    public function getOne($tour_id)
    {
        $query = (new Query);
        
    }

    public function create($data)
    {
        $tourModel = new self;
        $tourModel->title = $data['title'];
        $tourModel->alias = Common::convertToAlias($data['title']);
        $tourModel->intro_text = $data['intro_text'];
        $tourModel->departure_location = $data['departure_location'];
        $tourModel->destination = $data['destination'];
        $departure_date = $departure['departure_date'];
        if(strpos($departure_date, '/') > -1) {
            $arr_date = explode('/', $departure_date);
            $departure_date = $arr_date[2]. '-' .$arr_date[0]. '-' .$arr_date[1];
        }
        $tourModel->duration_days = $data['duration_days'];
        $tourModel->duration_nights = $data['duration_nights'];
        $tourModel->price = $data['price'];
        $tourModel->sale_price = $data['sale_price'];
        $tourModel->images = json_encode($data['images']);
        $tourModel->featured = $data['featured'];
        $tourModel->status = $data['status'];
        $tourModel->create_time = time();
        $tourModel->create_by = Yii::$app->user->identity->id;

        if($tourModel->save()) {
            $tour_id = $tourModel->id;
            // Create tour departures
            if(isset($data['departure'])) {
                (new TourDeparture)->create($tour_id, $data['departure']);
            }
            // Create tour details
            (new TourDetail)->create($tour_id, $data);
            return $tourModel->id;
        }
        return false;
    }

    public function edit($tour_id, $data)
    {
        $tourModel = self::findOne($tour_id);
        if(!$tourModel) return false;

        $tourModel->cat_id = $data['cat_id'];
        $tourModel->title = $data['title'];
        $tourModel->alias = Common::convertToAlias($data['title']);
        $tourModel->intro_text = $data['intro_text'];
        $tourModel->departure_location = $data['departure_location'];
        $tourModel->destination = $data['destination'];
        // $departure_date = $departure['departure_date'];
        // if(strpos($departure_date, '/') > -1) {
        //     $arr_date = explode('/', $departure_date);
        //     $departure_date = $arr_date[2]. '-' .$arr_date[0]. '-' .$arr_date[1];
        // }
        $tourModel->duration_days = $data['duration_days'];
        $tourModel->duration_nights = $data['duration_nights'];
        $tourModel->price = json_encode($data['price']);
        $tourModel->images = json_encode($data['images']);
        $tourModel->featured = $data['featured'];
        $tourModel->status = $data['status'];
        if($data['price']['sale'] > 0 && $data['price']['sale'] < $data['price']['base']) {
            $tourModel->sale = 1;
        }
        $tourModel->create_time = time();
        $tourModel->create_by = Yii::$app->user->identity->id;

        if($tourModel->save()) {
            $tour_id = $tourModel->id;
            // Create tour departures
            if(isset($data['departure'])) {
                (new TourDeparture)->create($tour_id, $data['departure']);
            }
            // Create tour details
            (new TourDetail)->create($tour_id, $data);
            return $tourModel->id;
        }
        return false;
    }

    public function getSaleTours($limit=10)
    {
        $query = self::find()
                ->where('sale = 1')
                ->limit($limit)
                ->orderBy(['create_time'=>SORT_DESC])
                ->all();
        return $query;
    }

    public function getDetail($tour_id)
    {
        $tour = self::findOne($tour_id);
        if($tour) {
            $tour = $tour->attributes;
            $array_destinations = explode(',', $tour['destination']);
            $tour['destinations'] = (new Destination)->getDestinations($array_destinations);
            $tour['details'] = TourDetail::findOne(['tour_id'=>$tour['id']]);
            $tour['departures'] = TourDeparture::findAll(['tour_id'=>$tour['id']]);
            return $tour;
        }
        return null;
    }

    public static function calcMoney($tour_id, $departure_price=false, $slot_adult=1, $slot_kid=0, $slot_baby=0)
    {
        $tour = self::findOne($tour_id);
        $price = json_decode($tour['price'], true);
        if($departure_price) {
            $price_unit = $departure_price;
        }
        else {
            $price_unit = ($price['sale'] > 0 && $price['sale'] < $price['base']) ? $price['sale'] : $price['base'];
        }
        $total = $price_unit*$slot_adult + $price['kid']*$slot_kid + $price['baby']*$slot_baby;
        return $total;
    }

    public static function getDepartureName($code)
    {
        switch ($code) {
            case self::HANOI:
                return 'Hà Nội';
            case self::DANANG:
                return 'Đà Nẵng';
            case self::HOCHIMINH:
                return 'Tp.Hồ Chí Minh';
        }
        return null;
    }

    public function getToursBydDestinationKeyword($destination_keyword)
    {
        $query = (new Query)
                ->select('tour_id')
                ->from('tbl_destination d')
                ->leftJoin('tbl_tour_destination l', 'd.id = l.destination_id')
                ->where(['LIKE', 'd.name', $destination_keyword])
                ->column();
        return $query;
    }

    
    public function getToursByDestinationId($des_id)
    {
        $query = (new Query)
            ->select('t.*')
            ->from('tbl_tour_destination td')
            ->leftJoin('tbl_tour t', 't.id = td.tour_id')
            ->where('td.destination_id = :did', [':did' => $des_id])
            ->andWhere('t.status=1')
            ->orderBy('create_time desc');
            
        return $query;
    }
}

backend/controllers/TourController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\data\Pagination;
use common\models\Tour;
use common\models\TourDetail;
use common\models\TourDeparture;
use common\models\Destination;

/**
 * Site controller
 */
class TourController extends Controller
{

    public function actionIndex()
    {   
        $search = Yii::$app->request->get();
        $query = (new Tour)->getByFilter($search);
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count()]);
			  $items = $query->offset($pages->offset)
			        ->limit($pages->limit)
                    ->all();

        return $this->render('index', array (
            'items'=>$items,
            'pages'=>$pages
        ) );
    }

    public function actionEdit()
    {   
        $tour_id = Yii::$app->request->get('tour_id');
        $tour = Tour::findOne($tour_id);

        if(!$tour) {
            return $this->redirect(Url::toRoute('tour/index'));
        }

        $tour = $tour->attributes;
        $tour['detail'] = TourDetail::findOne(['tour_id'=>$tour_id]);
        $tour['departure'] = TourDeparture::findAll(['tour_id'=>$tour_id]);
        $tour['destinations'] = (new Destination)->getDestinations( explode(',', $tour['destination']) );
        
        $data = Yii::$app->request->post();
        if($data) {
            // var_dump($data);die;
            $session = Yii::$app->session;
            if((new Tour())->edit($tour['id'], $data)) {
                $session->setFlash('form_error', 'Có lỗi xảy ra trong quá trình cập nhật. Vui lòng thử lại sau!');
            }
            else {
                $session->setFlash('form_error', 'Cập nhật thành công');
            }
            return $this->redirect(Url::current());
        }

        return $this->render('edit', array (
            'tour'=>$tour
        ) );
    }

    public function actionNew()
    {   
        if(Yii::$app->request->isPost) {
            $data = Yii::$app->request->post();
            $session = Yii::$app->session;
            
            $tour_id = (new Tour())->create($data);
            if($tour_id) {
                $session->setFlash('form_error', '<div class="alert alert-danger">Có lỗi xảy ra trong quá trình thêm mới. Vui lòng thử lại sau!</div>');
                return $this->redirect(Url::toRoute(['tour/edit', 'tour_id'=>$tour_id]));
            }
            else {
                $session->setFlash('form_error', '<div class="alert alert-success">Thêm mới thành công</div>');
            }
        }
        return $this->render('new');
    }
}

frontend/controllers/TourController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use yii\helpers\Url;
use yii\data\Pagination;
use common\models\Tour;
use common\models\Order;
use common\models\Customer;
use common\models\TourDeparture;
use common\models\Category;
use common\models\Common;
use common\models\Destination;

/**
 * Site controller
 */
class TourController extends Controller
{

    public function actionCategory()
    {
        $cat_id = Yii::$app->request->get('id');
        $cat = Category::findOne($cat_id);

        if(!$cat) {
            return $this->redirect(Url::home());
        }

        $search = array('cat_id'=>$cat_id);
        $query = (new Tour)->getByFilter($search);
        
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count()]);
        $items = $query->offset($pages->offset)
                ->limit($pages->limit)
                ->all();

        return $this->render('category', [
            'cat'=>$cat,
            'pages'=>$pages,
            'items'=>$items
        ]);
    }

    public function actionSearch()
    {
        $search = Yii::$app->request->get();
        $query = (new Tour)->getByFilter($search);
        
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count()]);
        $items = $query->offset($pages->offset)
                ->limit($pages->limit)
                ->all();

        return $this->render('search', [
            'pages'=>$pages,
            'items'=>$items
        ]);
    }

    public function actionDetail()
    {
        $tour_id = Yii::$app->request->get('tour_id');
        $tour = (new Tour)->getDetail($tour_id);
        
        return $this->render('detail', [
                'tour'=>$tour
            ]);
    }

    public function actionDestination()
    {
        $destination_id = Yii::$app->request->get('destination_id');
        $destination = Destination::findOne($destination_id);
        $query = (new Tour)->getToursByDestinationId($destination_id);
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count()]);
        $items = $query->offset($pages->offset)
                ->limit($pages->limit)
                ->all();
        
        return $this->render('destination', [
            'pages'=>$pages,
            'items'=>$items,
            'destination'=>$destination
        ]);
    }

    public function actionBooking()
    {
        $errors = array();
        $departure_id = Yii::$app->request->get('departure_id');
        $departure = TourDeparture::findOne($departure_id);
        if(!$departure) {
            return $this->redirect(Url::home());
        }
        $tour = (new TourDeparture)->getTourByDepartureId($departure_id);
        if(Yii::$app->request->isPost) {
            $data = Yii::$app->request->post();
            $customer_id = (new Customer)->create($data);
            $order_id = (new Order)->create($customer_id, $departure_id, $data);
            return $this->redirect(Url::toRoute(['tour/booking-success', 'order_id'=>$order_id]));
        }
        return $this->render('booking', [
            'errors'=>$errors,
            'departure'=>$departure,
            'tour'=>$tour
        ]);
    }

    public function actionBookingSuccess()
    {
        $order_id = Yii::$app->request->get('order_id');
        $query = (new Order)->getByFilter([
                'order_id'=>$order_id
            ]);
        $order = $query->one();
        return $this->render('booking-success', ['order'=>$order]);
    }

    // AJAX
    public function actionAjaxCalBookingAmount()
    {
        if(Yii::$app->request->isPost) {
            $params = Yii::$app->request->post();
            $departure_id = $params['departure_id'];
            $slot_adult = $params['slot_adult'];
            $slot_child = $params['slot_child'];
            $slot_babay = $params['slot_babay'];
            $departure = TourDeparture::findOne($departure_id);
            if($departure) {
                $price_unit = $departure['sale_price'] && $departure['sale_price'] < $departure['price'] ? $departure['sale_price'] : $departure['price'];
                $amount = Tour::calcMoney($departure['tour_id'], $price_unit, $slot_adult, $slot_child, $slot_babay);
                $amount = Common::formatVnd($amount);
                return $amount;
            }
        }
        return false;
    }
}

backend/views/tour/_form.php
<?php  
use yii\helpers\Url;
?>
<form action="" method="POST">
    <div class="card">
        <div class="card-header">
            <ul class="nav nav-pills" id="myTab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="main-tab" data-toggle="tab" href="#details" role="tab">Chi tiết</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#tab2" role="tab">Lịch trình</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#tab3" role="tab">Lịch khởi hành</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#tab4" role="tab">Thông tin</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="gallery-tab" data-toggle="tab" href="#tab5" role="tab">Thư viện ảnh</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="price-tab" data-toggle="tab" href="#tab6" role="tab">Bảng giá</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="review-tab" data-toggle="tab" href="#tab7" role="tab">Đánh giá</a>
                </li>
            </ul>
        </div>
        <div class="card-body">
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="details" role="tabpanel">
                    <?php echo $this->render('./inc/details', ['tour'=>$tour]) ?>
                </div>
                <div class="tab-pane fade" id="tab2" role="tabpanel">
                    <?php echo $this->render('./inc/itinerary', ['tour'=>$tour]) ?>
                </div>
                <div class="tab-pane fade" id="tab3" role="tabpanel">
                    <?php echo $this->render('./inc/departure', ['tour'=>$tour]) ?>
                </div>
                <div class="tab-pane fade" id="tab4" role="tabpanel">
                    <?php echo $this->render('./inc/information', ['tour'=>$tour]) ?>
                </div>
                <div class="tab-pane fade" id="tab5" role="tabpanel">
                    <?php echo $this->render('./inc/gallery', ['tour'=>$tour]) ?>
                </div>
                <div class="tab-pane fade" id="tab6" role="tabpanel">
                    <?php echo $this->render('./inc/price', ['tour'=>$tour]) ?>
                </div>
                <div class="tab-pane fade" id="tab7" role="tabpanel"></div>
            </div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-success">Lưu</button>
        </div>
    </div>
</form>
<?php 
$this->registerJsFile(Url::to('@web/js/filemanager.js'), ['depends'=>[yii\web\JqueryAsset::className()]]);

backend/views/tour/edit.php
<?php  
$tour['itinerary'] = json_decode($tour['detail']['itinerary'], true);
$tour['images'] = json_decode($tour['images'], true);
$tour['price'] = json_decode($tour['price'], true);

echo $this->render('_form', ['tour'=>$tour]);

backend/views/tour/index.php
<?php  
use yii\helpers\Url;
?>
<div>
    <a href="<?php echo Url::toRoute('tour/new') ?>" class="btn btn-success">Thêm mới</a>
</div>
<?php if($items) : ?>
    <table class="table">
        <thead>
            <tr>
                <th></th>
                <th>Tiêu đề</th>
                <th>Giá</th>
                <th>Giảm giá</th>
                <th>Thời lượng</th>
                <th>Nổi bật</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($items as $k => $item) : 
            $price = json_decode($item['price'], true); ?>

            <tr>
                <td></td>
                <td><a href="<?php echo Url::toRoute(['tour/edit', 'tour_id'=>$item['id']]) ?>"><?php echo $item['title'] ?></a></td>
                <td><?php echo $price['base'] ?></td>
                <td><?php echo $price['sale'] ?></td>
                <td><?php echo $item['duration_days'] ?> Ngày, <?php echo $item['duration_nights'] ?> Đêm</td>
                <td><?php echo $item['featured'] ? 'Có' : 'Không' ?></td>
            </tr>

        <?php endforeach ?>
        </tbody>
    </table>
<?php endif ?>

backend/views/tour/new.php
<?php  
$tour = Yii::$app->request->post();

echo $this->render('_form', ['tour'=>$tour]);